# Simplified nixpacks config - backend only
[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
  "cd excel_ai_backend && pip install --no-cache-dir --disable-pip-version-check -r requirements.txt"
]

[start]
cmd = "cd excel_ai_backend && python -m flask run --host=0.0.0.0 --port=$PORT"

[variables]
FLASK_ENV = "production"
PYTHONPATH = "/app/excel_ai_backend"