[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
FLASK_ENV = "production"
PYTHONPATH = "/app/excel_ai_backend"
