services:
  # Backend API
  - type: web
    name: excel-ai-backend
    runtime: python3
    buildCommand: "cd excel_ai_backend && pip install -r requirements.txt"
    startCommand: "cd excel_ai_backend && python -m flask run --host=0.0.0.0 --port=$PORT"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src/excel_ai_backend
      - key: OPENAI_API_KEY
        sync: false  # Set this manually in Render dashboard
    healthCheckPath: /api/health

  # Frontend
  - type: web
    name: excel-ai-frontend
    runtime: node
    buildCommand: "cd excel-ai-frontend && npm ci && npm run build"
    staticPublishPath: excel-ai-frontend/dist
    envVars:
      - key: NODE_VERSION
        value: "20"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://excel-ai-backend.onrender.com/api/*
      - type: rewrite  
        source: /*
        destination: /index.html
