import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { 
  Database, 
  BarChart3, 
  PieChart, 
  Zap, 
  Shield, 
  Sparkles,
  ArrowRight,
  Play,
  CheckCircle,
  Users,
  TrendingUp,
  Brain
} from 'lucide-react'

export function LandingPage({ onGetStarted, onTryDemo, onLearnMore }) {
  const [hoveredFeature, setHoveredFeature] = useState(null)

  const features = [
    {
      icon: Database,
      title: "Connect Any Data Source",
      description: "Excel, CSV, Google Sheets, APIs - bring all your data together seamlessly",
      category: "Connect"
    },
    {
      icon: Brain,
      title: "AI-Powered Analysis",
      description: "Get instant insights, predictions, and recommendations from your data",
      category: "Analyze",
      featured: true
    },
    {
      icon: BarChart3,
      title: "Beautiful Visualizations",
      description: "Create stunning charts and dashboards with just a few clicks",
      category: "Visualize"
    },
    {
      icon: Zap,
      title: "Smart Data Prep",
      description: "Clean, transform, and enrich your data automatically",
      category: "Prepare"
    },
    {
      icon: Sparkles,
      title: "AI Text Enhancement",
      description: "Sentiment analysis, summaries, and smart content generation",
      category: "Enrich"
    },
    {
      icon: PieChart,
      title: "Powerful Tools",
      description: "Excel formulas, SQL queries, VBA scripts generated by AI",
      category: "Tools"
    }
  ]

  const stats = [
    { icon: Users, value: "10,000+", label: "Happy Users" },
    { icon: TrendingUp, value: "2M+", label: "Data Points Analyzed" },
    { icon: Zap, value: "95%", label: "Time Saved" }
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50">
      {/* Hero Section */}
      <div className="container mx-auto px-4 pt-16 pb-24">
        <div className="text-center mb-16">
          <div className="flex justify-center mb-6">
            <Badge variant="outline" className="bg-blue-100 text-blue-800 border-blue-200">
              🚀 AI-Powered Business Intelligence Platform
            </Badge>
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6 leading-tight">
            Transform Your
            <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              {" "}Data Into Insights
            </span>
          </h1>
          
          <p className="text-xl md:text-2xl text-gray-600 mb-8 max-w-3xl mx-auto leading-relaxed">
            DataSense AI is your complete business intelligence platform. 
            Connect any data source, get AI-powered analysis, and create beautiful visualizations 
            — all without writing a single line of code.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center mb-12">
            <Button 
              size="lg" 
              className="text-lg px-8 py-4 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
              onClick={onGetStarted}
            >
              Get Started Free
              <ArrowRight className="ml-2 h-5 w-5" />
            </Button>
            
            <Button 
              variant="outline" 
              size="lg" 
              className="text-lg px-8 py-4"
              onClick={onTryDemo}
            >
              <Play className="mr-2 h-5 w-5" />
              Try Demo
            </Button>
          </div>

          {/* Social Proof */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-2xl mx-auto">
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div className="flex justify-center mb-2">
                  <stat.icon className="h-8 w-8 text-blue-600" />
                </div>
                <div className="text-2xl font-bold text-gray-900">{stat.value}</div>
                <div className="text-sm text-gray-600">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Feature Grid */}
        <div className="mb-20">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Everything You Need for Data Analysis
            </h2>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">
              Six powerful modules working together to turn your raw data into actionable business insights
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((feature, index) => (
              <Card 
                key={index}
                className={`relative transition-all duration-300 hover:scale-105 hover:shadow-xl cursor-pointer bg-white ${
                  feature.featured ? 'ring-2 ring-blue-500 bg-gradient-to-br from-blue-50 to-purple-50' : ''
                }`}
                onMouseEnter={() => setHoveredFeature(index)}
                onMouseLeave={() => setHoveredFeature(null)}
              >
                {feature.featured && (
                  <div className="absolute -top-3 left-4">
                    <Badge className="bg-gradient-to-r from-blue-600 to-purple-600 text-white border-0">
                      ⭐ Most Popular
                    </Badge>
                  </div>
                )}
                
                <CardHeader className="text-center">
                  <div className="mx-auto mb-4 p-3 bg-white rounded-full shadow-md">
                    <feature.icon className={`h-8 w-8 ${
                      feature.featured ? 'text-purple-600' : 'text-blue-600'
                    }`} />
                  </div>
                  <CardTitle className="text-xl mb-2 text-gray-900 dark:text-gray-100">{feature.title}</CardTitle>
                  <Badge variant="secondary" className="w-fit mx-auto bg-gray-100 text-gray-800 border-0">
                    {feature.category}
                  </Badge>
                </CardHeader>
                
                <CardContent>
                  <CardDescription className="text-center text-base text-gray-700 dark:text-gray-300">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>

        {/* Benefits Section */}
        <div className="bg-white rounded-2xl shadow-xl p-8 md:p-12 mb-20">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <div>
              <h3 className="text-3xl font-bold text-gray-900 mb-6">
                Why Choose DataSense AI?
              </h3>
              
              <div className="space-y-4">
                {[
                  "No coding required - intuitive drag-and-drop interface",
                  "AI-powered insights that save hours of manual analysis",
                  "Connect to 50+ data sources including Excel, CSV, APIs",
                  "Enterprise-grade security with data encryption",
                  "Real-time collaboration with your team",
                  "Export results to any format you need"
                ].map((benefit, index) => (
                  <div key={index} className="flex items-start space-x-3">
                    <CheckCircle className="h-6 w-6 text-green-500 mt-0.5 flex-shrink-0" />
                    <span className="text-gray-700">{benefit}</span>
                  </div>
                ))}
              </div>
            </div>
            
            <div className="bg-gradient-to-br from-blue-100 to-purple-100 rounded-xl p-8 text-center">
              <div className="text-4xl mb-4">📊</div>
              <h4 className="text-xl font-semibold text-gray-900 mb-2">
                Ready to Get Started?
              </h4>
              <p className="text-gray-600 mb-6">
                Join thousands of businesses already using DataSense AI to make better decisions.
              </p>
              <Button 
                className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
                onClick={onGetStarted}
              >
                Start Your Free Trial
                <ArrowRight className="ml-2 h-4 w-4" />
              </Button>
            </div>
          </div>
        </div>

        {/* CTA Section */}
        <div className="text-center">
          <div className="bg-gradient-to-r from-blue-600 to-purple-600 rounded-2xl p-8 md:p-12 text-white">
            <h3 className="text-3xl md:text-4xl font-bold mb-4">
              Ready to Transform Your Data?
            </h3>
            <p className="text-xl mb-8 opacity-90">
              Start your free trial today. No credit card required.
            </p>
            
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                variant="secondary"
                className="text-lg px-8 py-4 bg-white text-gray-900 hover:bg-gray-100"
                onClick={onGetStarted}
              >
                Get Started Free
                <ArrowRight className="ml-2 h-5 w-5" />
              </Button>
              
              <Button 
                size="lg" 
                variant="outline"
                className="text-lg px-8 py-4 border-white text-white hover:bg-white hover:text-gray-900"
                onClick={onLearnMore}
              >
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default LandingPage
